spring:
  application:
    name: card
  sql:
    init:
      mode: always
  r2dbc:
    enabled: true
    url: r2dbc:h2:mem:///testdb;MODE=MySQL
    username: sa
    password:
    pool:
      enabled: true
      max-size: 20
  data:
    r2dbc.repositories:
      enabled: true
  main.allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/swagger-ui/

springdoc:
  api-docs:
    path: /api-docs
    groups.enabled: true
  swagger-ui:
    enabled: true
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


server:
  port: 8094


logging.level:
  root: DEBUG
  org:
    hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG
    springframework:
      data.r2dbc: DEBUG