spring:
  application:
    name: card
  sql:
    init:
      mode: always
  r2dbc:
    enabled: true
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    pool:
      enabled: true
      max-size: 20
  data:
    r2dbc.repositories:
      enabled: true
  main.allow-bean-definition-overriding: true


server:
  port: 8094


logging.level:
  root: INFO
  org:
    hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG
    springframework:
      data.r2dbc: DEBUG